project:
  name: SmallBun-快速开发平台 #名称
  version: v1.0.0 #版本
  powered-by: http://www.smallbun.org
logging:
  config: classpath:logback-spring.xml  #指定配置文件
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#
spring:
  profiles:
    active: prod
  session:
    store-type: redis #session 存储类型
  redis: #redis
    host: 47.92.112.34
    password: chenbaipay
    port: 6379
  resources:
    chain:
      strategy:
        content:
          #资源名-md5
          enabled: true
      cache: true
  thymeleaf:
    cache: false #不进行缓存
    prefix: classpath:views/ #更改模板位置为views
#------------------------------------------#
#                                          #
#          SmallBun自定义配置                #
#                                          #
#------------------------------------------#
smallbun:
  kaptcha:
    text-producer-char-length: 4

#------------------------------------------#
#                                          #
#            mybatis plus 配置              #
#                                          #
#------------------------------------------#
#mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.smallbun.fast.**.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: MYSQL
    refresh: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true #设置为true为打开延迟加载 实体类必须加上这个注解@JsonIgnoreProperties(value = {"handler"}) 否则将会报com.fasterxml.jackson.databind.exc.InvalidDefinitionException错误
    aggressive-lazy-loading: false #将积极加载改为消极加载，即延迟加载



